package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class BizDocPartnerKey implements Serializable {
    private String docId;

    private String partnerRoleId;

    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_doc_partner
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getDocId() {
        return docId;
    }

    public void setDocId(String docId) {
        this.docId = docId;
    }

    @CodeFieldNotes("")
    public String getPartnerRoleId() {
        return partnerRoleId;
    }

    public void setPartnerRoleId(String partnerRoleId) {
        this.partnerRoleId = partnerRoleId;
    }

    @CodeFieldNotes("")
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
}