package cn.nkpro.tfms.platform.model.po;

import java.util.ArrayList;
import java.util.List;

public class BizDocSubjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public BizDocSubjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDocIdIsNull() {
            addCriterion("DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andDocIdIsNotNull() {
            addCriterion("DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDocIdEqualTo(String value) {
            addCriterion("DOC_ID =", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotEqualTo(String value) {
            addCriterion("DOC_ID <>", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThan(String value) {
            addCriterion("DOC_ID >", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_ID >=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThan(String value) {
            addCriterion("DOC_ID <", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThanOrEqualTo(String value) {
            addCriterion("DOC_ID <=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLike(String value) {
            addCriterion("DOC_ID like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotLike(String value) {
            addCriterion("DOC_ID not like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdIn(List<String> values) {
            addCriterion("DOC_ID in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotIn(List<String> values) {
            addCriterion("DOC_ID not in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdBetween(String value1, String value2) {
            addCriterion("DOC_ID between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotBetween(String value1, String value2) {
            addCriterion("DOC_ID not between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdIsNull() {
            addCriterion("SUBJECT_REF_DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdIsNotNull() {
            addCriterion("SUBJECT_REF_DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdEqualTo(String value) {
            addCriterion("SUBJECT_REF_DOC_ID =", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdNotEqualTo(String value) {
            addCriterion("SUBJECT_REF_DOC_ID <>", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdGreaterThan(String value) {
            addCriterion("SUBJECT_REF_DOC_ID >", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_REF_DOC_ID >=", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdLessThan(String value) {
            addCriterion("SUBJECT_REF_DOC_ID <", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_REF_DOC_ID <=", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdLike(String value) {
            addCriterion("SUBJECT_REF_DOC_ID like", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdNotLike(String value) {
            addCriterion("SUBJECT_REF_DOC_ID not like", value, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdIn(List<String> values) {
            addCriterion("SUBJECT_REF_DOC_ID in", values, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdNotIn(List<String> values) {
            addCriterion("SUBJECT_REF_DOC_ID not in", values, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdBetween(String value1, String value2) {
            addCriterion("SUBJECT_REF_DOC_ID between", value1, value2, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefDocIdNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_REF_DOC_ID not between", value1, value2, "subjectRefDocId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdIsNull() {
            addCriterion("SUBJECT_REF_ITEM_ID is null");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdIsNotNull() {
            addCriterion("SUBJECT_REF_ITEM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdEqualTo(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID =", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdNotEqualTo(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID <>", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdGreaterThan(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID >", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID >=", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdLessThan(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID <", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID <=", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdLike(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID like", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdNotLike(String value) {
            addCriterion("SUBJECT_REF_ITEM_ID not like", value, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdIn(List<String> values) {
            addCriterion("SUBJECT_REF_ITEM_ID in", values, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdNotIn(List<String> values) {
            addCriterion("SUBJECT_REF_ITEM_ID not in", values, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdBetween(String value1, String value2) {
            addCriterion("SUBJECT_REF_ITEM_ID between", value1, value2, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefItemIdNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_REF_ITEM_ID not between", value1, value2, "subjectRefItemId");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyIsNull() {
            addCriterion("SUBJECT_REF_CLASSIFY is null");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyIsNotNull() {
            addCriterion("SUBJECT_REF_CLASSIFY is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyEqualTo(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY =", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyNotEqualTo(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY <>", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyGreaterThan(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY >", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY >=", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyLessThan(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY <", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY <=", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyLike(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY like", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyNotLike(String value) {
            addCriterion("SUBJECT_REF_CLASSIFY not like", value, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyIn(List<String> values) {
            addCriterion("SUBJECT_REF_CLASSIFY in", values, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyNotIn(List<String> values) {
            addCriterion("SUBJECT_REF_CLASSIFY not in", values, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyBetween(String value1, String value2) {
            addCriterion("SUBJECT_REF_CLASSIFY between", value1, value2, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectRefClassifyNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_REF_CLASSIFY not between", value1, value2, "subjectRefClassify");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNull() {
            addCriterion("SUBJECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNotNull() {
            addCriterion("SUBJECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameEqualTo(String value) {
            addCriterion("SUBJECT_NAME =", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotEqualTo(String value) {
            addCriterion("SUBJECT_NAME <>", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThan(String value) {
            addCriterion("SUBJECT_NAME >", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("SUBJECT_NAME >=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThan(String value) {
            addCriterion("SUBJECT_NAME <", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("SUBJECT_NAME <=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLike(String value) {
            addCriterion("SUBJECT_NAME like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotLike(String value) {
            addCriterion("SUBJECT_NAME not like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIn(List<String> values) {
            addCriterion("SUBJECT_NAME in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotIn(List<String> values) {
            addCriterion("SUBJECT_NAME not in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameBetween(String value1, String value2) {
            addCriterion("SUBJECT_NAME between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotBetween(String value1, String value2) {
            addCriterion("SUBJECT_NAME not between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceIsNull() {
            addCriterion("SUBJECT_UNIT_PRICE is null");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceIsNotNull() {
            addCriterion("SUBJECT_UNIT_PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceEqualTo(Double value) {
            addCriterion("SUBJECT_UNIT_PRICE =", value, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceNotEqualTo(Double value) {
            addCriterion("SUBJECT_UNIT_PRICE <>", value, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceGreaterThan(Double value) {
            addCriterion("SUBJECT_UNIT_PRICE >", value, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceGreaterThanOrEqualTo(Double value) {
            addCriterion("SUBJECT_UNIT_PRICE >=", value, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceLessThan(Double value) {
            addCriterion("SUBJECT_UNIT_PRICE <", value, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceLessThanOrEqualTo(Double value) {
            addCriterion("SUBJECT_UNIT_PRICE <=", value, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceIn(List<Double> values) {
            addCriterion("SUBJECT_UNIT_PRICE in", values, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceNotIn(List<Double> values) {
            addCriterion("SUBJECT_UNIT_PRICE not in", values, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceBetween(Double value1, Double value2) {
            addCriterion("SUBJECT_UNIT_PRICE between", value1, value2, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectUnitPriceNotBetween(Double value1, Double value2) {
            addCriterion("SUBJECT_UNIT_PRICE not between", value1, value2, "subjectUnitPrice");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityIsNull() {
            addCriterion("SUBJECT_QUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityIsNotNull() {
            addCriterion("SUBJECT_QUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityEqualTo(Integer value) {
            addCriterion("SUBJECT_QUANTITY =", value, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityNotEqualTo(Integer value) {
            addCriterion("SUBJECT_QUANTITY <>", value, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityGreaterThan(Integer value) {
            addCriterion("SUBJECT_QUANTITY >", value, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("SUBJECT_QUANTITY >=", value, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityLessThan(Integer value) {
            addCriterion("SUBJECT_QUANTITY <", value, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("SUBJECT_QUANTITY <=", value, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityIn(List<Integer> values) {
            addCriterion("SUBJECT_QUANTITY in", values, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityNotIn(List<Integer> values) {
            addCriterion("SUBJECT_QUANTITY not in", values, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityBetween(Integer value1, Integer value2) {
            addCriterion("SUBJECT_QUANTITY between", value1, value2, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("SUBJECT_QUANTITY not between", value1, value2, "subjectQuantity");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalIsNull() {
            addCriterion("SUBJECT_SUBTOTAL is null");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalIsNotNull() {
            addCriterion("SUBJECT_SUBTOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalEqualTo(Double value) {
            addCriterion("SUBJECT_SUBTOTAL =", value, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalNotEqualTo(Double value) {
            addCriterion("SUBJECT_SUBTOTAL <>", value, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalGreaterThan(Double value) {
            addCriterion("SUBJECT_SUBTOTAL >", value, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalGreaterThanOrEqualTo(Double value) {
            addCriterion("SUBJECT_SUBTOTAL >=", value, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalLessThan(Double value) {
            addCriterion("SUBJECT_SUBTOTAL <", value, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalLessThanOrEqualTo(Double value) {
            addCriterion("SUBJECT_SUBTOTAL <=", value, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalIn(List<Double> values) {
            addCriterion("SUBJECT_SUBTOTAL in", values, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalNotIn(List<Double> values) {
            addCriterion("SUBJECT_SUBTOTAL not in", values, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalBetween(Double value1, Double value2) {
            addCriterion("SUBJECT_SUBTOTAL between", value1, value2, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andSubjectSubtotalNotBetween(Double value1, Double value2) {
            addCriterion("SUBJECT_SUBTOTAL not between", value1, value2, "subjectSubtotal");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Long value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Long value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Long value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Long value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Long> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Long> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_doc_subject
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}