package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class BizDocSubject extends BizDocSubjectKey implements Serializable {
    private String subjectRefClassify;

    private String subjectName;

    private Double subjectUnitPrice;

    private Integer subjectQuantity;

    private Double subjectSubtotal;

    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_doc_subject
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getSubjectRefClassify() {
        return subjectRefClassify;
    }

    public void setSubjectRefClassify(String subjectRefClassify) {
        this.subjectRefClassify = subjectRefClassify;
    }

    @CodeFieldNotes("")
    public String getSubjectName() {
        return subjectName;
    }

    public void setSubjectName(String subjectName) {
        this.subjectName = subjectName;
    }

    @CodeFieldNotes("")
    public Double getSubjectUnitPrice() {
        return subjectUnitPrice;
    }

    public void setSubjectUnitPrice(Double subjectUnitPrice) {
        this.subjectUnitPrice = subjectUnitPrice;
    }

    @CodeFieldNotes("")
    public Integer getSubjectQuantity() {
        return subjectQuantity;
    }

    public void setSubjectQuantity(Integer subjectQuantity) {
        this.subjectQuantity = subjectQuantity;
    }

    @CodeFieldNotes("")
    public Double getSubjectSubtotal() {
        return subjectSubtotal;
    }

    public void setSubjectSubtotal(Double subjectSubtotal) {
        this.subjectSubtotal = subjectSubtotal;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }
}