package cn.nkpro.tfms.platform.model.po;

import java.util.ArrayList;
import java.util.List;

public class BizOrgExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public BizOrgExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDocIdIsNull() {
            addCriterion("DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andDocIdIsNotNull() {
            addCriterion("DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDocIdEqualTo(String value) {
            addCriterion("DOC_ID =", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotEqualTo(String value) {
            addCriterion("DOC_ID <>", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThan(String value) {
            addCriterion("DOC_ID >", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_ID >=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThan(String value) {
            addCriterion("DOC_ID <", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLessThanOrEqualTo(String value) {
            addCriterion("DOC_ID <=", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdLike(String value) {
            addCriterion("DOC_ID like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotLike(String value) {
            addCriterion("DOC_ID not like", value, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdIn(List<String> values) {
            addCriterion("DOC_ID in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotIn(List<String> values) {
            addCriterion("DOC_ID not in", values, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdBetween(String value1, String value2) {
            addCriterion("DOC_ID between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andDocIdNotBetween(String value1, String value2) {
            addCriterion("DOC_ID not between", value1, value2, "docId");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("ORG_CODE is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("ORG_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("ORG_CODE =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("ORG_CODE <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("ORG_CODE >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_CODE >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("ORG_CODE <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("ORG_CODE <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("ORG_CODE like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("ORG_CODE not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("ORG_CODE in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("ORG_CODE not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("ORG_CODE between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("ORG_CODE not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorIsNull() {
            addCriterion("ORG_SUPERIOR is null");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorIsNotNull() {
            addCriterion("ORG_SUPERIOR is not null");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorEqualTo(String value) {
            addCriterion("ORG_SUPERIOR =", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorNotEqualTo(String value) {
            addCriterion("ORG_SUPERIOR <>", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorGreaterThan(String value) {
            addCriterion("ORG_SUPERIOR >", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_SUPERIOR >=", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorLessThan(String value) {
            addCriterion("ORG_SUPERIOR <", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorLessThanOrEqualTo(String value) {
            addCriterion("ORG_SUPERIOR <=", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorLike(String value) {
            addCriterion("ORG_SUPERIOR like", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorNotLike(String value) {
            addCriterion("ORG_SUPERIOR not like", value, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorIn(List<String> values) {
            addCriterion("ORG_SUPERIOR in", values, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorNotIn(List<String> values) {
            addCriterion("ORG_SUPERIOR not in", values, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorBetween(String value1, String value2) {
            addCriterion("ORG_SUPERIOR between", value1, value2, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgSuperiorNotBetween(String value1, String value2) {
            addCriterion("ORG_SUPERIOR not between", value1, value2, "orgSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIsNull() {
            addCriterion("ORG_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIsNotNull() {
            addCriterion("ORG_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andOrgTypeEqualTo(String value) {
            addCriterion("ORG_TYPE =", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotEqualTo(String value) {
            addCriterion("ORG_TYPE <>", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeGreaterThan(String value) {
            addCriterion("ORG_TYPE >", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_TYPE >=", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLessThan(String value) {
            addCriterion("ORG_TYPE <", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLessThanOrEqualTo(String value) {
            addCriterion("ORG_TYPE <=", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeLike(String value) {
            addCriterion("ORG_TYPE like", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotLike(String value) {
            addCriterion("ORG_TYPE not like", value, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeIn(List<String> values) {
            addCriterion("ORG_TYPE in", values, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotIn(List<String> values) {
            addCriterion("ORG_TYPE not in", values, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeBetween(String value1, String value2) {
            addCriterion("ORG_TYPE between", value1, value2, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgTypeNotBetween(String value1, String value2) {
            addCriterion("ORG_TYPE not between", value1, value2, "orgType");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNull() {
            addCriterion("ORG_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNotNull() {
            addCriterion("ORG_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEqualTo(String value) {
            addCriterion("ORG_NAME =", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotEqualTo(String value) {
            addCriterion("ORG_NAME <>", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThan(String value) {
            addCriterion("ORG_NAME >", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_NAME >=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThan(String value) {
            addCriterion("ORG_NAME <", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThanOrEqualTo(String value) {
            addCriterion("ORG_NAME <=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLike(String value) {
            addCriterion("ORG_NAME like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotLike(String value) {
            addCriterion("ORG_NAME not like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameIn(List<String> values) {
            addCriterion("ORG_NAME in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotIn(List<String> values) {
            addCriterion("ORG_NAME not in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameBetween(String value1, String value2) {
            addCriterion("ORG_NAME between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotBetween(String value1, String value2) {
            addCriterion("ORG_NAME not between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameIsNull() {
            addCriterion("ORG_POSITION_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameIsNotNull() {
            addCriterion("ORG_POSITION_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameEqualTo(String value) {
            addCriterion("ORG_POSITION_NAME =", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameNotEqualTo(String value) {
            addCriterion("ORG_POSITION_NAME <>", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameGreaterThan(String value) {
            addCriterion("ORG_POSITION_NAME >", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_POSITION_NAME >=", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameLessThan(String value) {
            addCriterion("ORG_POSITION_NAME <", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameLessThanOrEqualTo(String value) {
            addCriterion("ORG_POSITION_NAME <=", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameLike(String value) {
            addCriterion("ORG_POSITION_NAME like", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameNotLike(String value) {
            addCriterion("ORG_POSITION_NAME not like", value, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameIn(List<String> values) {
            addCriterion("ORG_POSITION_NAME in", values, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameNotIn(List<String> values) {
            addCriterion("ORG_POSITION_NAME not in", values, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameBetween(String value1, String value2) {
            addCriterion("ORG_POSITION_NAME between", value1, value2, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionNameNotBetween(String value1, String value2) {
            addCriterion("ORG_POSITION_NAME not between", value1, value2, "orgPositionName");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorIsNull() {
            addCriterion("ORG_POSITION_SUPERIOR is null");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorIsNotNull() {
            addCriterion("ORG_POSITION_SUPERIOR is not null");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorEqualTo(String value) {
            addCriterion("ORG_POSITION_SUPERIOR =", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorNotEqualTo(String value) {
            addCriterion("ORG_POSITION_SUPERIOR <>", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorGreaterThan(String value) {
            addCriterion("ORG_POSITION_SUPERIOR >", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_POSITION_SUPERIOR >=", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorLessThan(String value) {
            addCriterion("ORG_POSITION_SUPERIOR <", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorLessThanOrEqualTo(String value) {
            addCriterion("ORG_POSITION_SUPERIOR <=", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorLike(String value) {
            addCriterion("ORG_POSITION_SUPERIOR like", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorNotLike(String value) {
            addCriterion("ORG_POSITION_SUPERIOR not like", value, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorIn(List<String> values) {
            addCriterion("ORG_POSITION_SUPERIOR in", values, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorNotIn(List<String> values) {
            addCriterion("ORG_POSITION_SUPERIOR not in", values, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorBetween(String value1, String value2) {
            addCriterion("ORG_POSITION_SUPERIOR between", value1, value2, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPositionSuperiorNotBetween(String value1, String value2) {
            addCriterion("ORG_POSITION_SUPERIOR not between", value1, value2, "orgPositionSuperior");
            return (Criteria) this;
        }

        public Criteria andOrgPathIsNull() {
            addCriterion("ORG_PATH is null");
            return (Criteria) this;
        }

        public Criteria andOrgPathIsNotNull() {
            addCriterion("ORG_PATH is not null");
            return (Criteria) this;
        }

        public Criteria andOrgPathEqualTo(String value) {
            addCriterion("ORG_PATH =", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathNotEqualTo(String value) {
            addCriterion("ORG_PATH <>", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathGreaterThan(String value) {
            addCriterion("ORG_PATH >", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathGreaterThanOrEqualTo(String value) {
            addCriterion("ORG_PATH >=", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathLessThan(String value) {
            addCriterion("ORG_PATH <", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathLessThanOrEqualTo(String value) {
            addCriterion("ORG_PATH <=", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathLike(String value) {
            addCriterion("ORG_PATH like", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathNotLike(String value) {
            addCriterion("ORG_PATH not like", value, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathIn(List<String> values) {
            addCriterion("ORG_PATH in", values, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathNotIn(List<String> values) {
            addCriterion("ORG_PATH not in", values, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathBetween(String value1, String value2) {
            addCriterion("ORG_PATH between", value1, value2, "orgPath");
            return (Criteria) this;
        }

        public Criteria andOrgPathNotBetween(String value1, String value2) {
            addCriterion("ORG_PATH not between", value1, value2, "orgPath");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Long value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Long value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Long value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Long value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Long> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Long> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_org
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}