package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class BizOrg extends BizOrgKey implements Serializable {
    private String orgSuperior;

    private String orgType;

    private String orgName;

    private String orgPositionName;

    private String orgPositionSuperior;

    private String orgPath;

    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_org
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getOrgSuperior() {
        return orgSuperior;
    }

    public void setOrgSuperior(String orgSuperior) {
        this.orgSuperior = orgSuperior;
    }

    @CodeFieldNotes("")
    public String getOrgType() {
        return orgType;
    }

    public void setOrgType(String orgType) {
        this.orgType = orgType;
    }

    @CodeFieldNotes("")
    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    @CodeFieldNotes("")
    public String getOrgPositionName() {
        return orgPositionName;
    }

    public void setOrgPositionName(String orgPositionName) {
        this.orgPositionName = orgPositionName;
    }

    @CodeFieldNotes("")
    public String getOrgPositionSuperior() {
        return orgPositionSuperior;
    }

    public void setOrgPositionSuperior(String orgPositionSuperior) {
        this.orgPositionSuperior = orgPositionSuperior;
    }

    @CodeFieldNotes("")
    public String getOrgPath() {
        return orgPath;
    }

    public void setOrgPath(String orgPath) {
        this.orgPath = orgPath;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }
}