package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class BizPartner implements Serializable {
    private String partnerId;

    /**
     * 1 自然人 2 法人 3 组织机构
     *
     * @mbggenerated
     */
    private String partnerType;

    private String partnerName;

    private String remark;

    private Long createdTime;

    private Long updatedTime;

    private String partnerTags;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table biz_partner
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getPartnerId() {
        return partnerId;
    }

    public void setPartnerId(String partnerId) {
        this.partnerId = partnerId;
    }

    /**
     * 获取 1 自然人 2 法人 3 组织机构
     *
     * @return 1 自然人 2 法人 3 组织机构
     *
     * @mbggenerated
     */
    @CodeFieldNotes("1 自然人 2 法人 3 组织机构")
    public String getPartnerType() {
        return partnerType;
    }

    /**
     * 设置 1 自然人 2 法人 3 组织机构
     *
     * @return 1 自然人 2 法人 3 组织机构
     *
     * @mbggenerated
     */
    public void setPartnerType(String partnerType) {
        this.partnerType = partnerType;
    }

    @CodeFieldNotes("")
    public String getPartnerName() {
        return partnerName;
    }

    public void setPartnerName(String partnerName) {
        this.partnerName = partnerName;
    }

    @CodeFieldNotes("")
    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    @CodeFieldNotes("")
    public Long getCreatedTime() {
        return createdTime;
    }

    public void setCreatedTime(Long createdTime) {
        this.createdTime = createdTime;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    @CodeFieldNotes("")
    public String getPartnerTags() {
        return partnerTags;
    }

    public void setPartnerTags(String partnerTags) {
        this.partnerTags = partnerTags;
    }
}