package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DefDocPartnerRole extends DefDocPartnerRoleKey implements Serializable {
    private String typeDesc;

    private String rule;

    private Integer min;

    private Integer max;

    private String refObjectType;

    /**
     * 是否为单据交易伙伴标识
     *
     * @mbggenerated
     */
    private Integer partnerFlag;

    private String programSpEL;

    private Integer programMode;

    /**
     * 只读条件表达式
     *
     * @mbggenerated
     */
    private String readonlyEval;

    /**
     * 选择框配置
     *
     * @mbggenerated
     */
    private String modalSelectorOptions;

    private String indexKey;

    private Long updatedTime;

    private Integer orderBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_doc_partner_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getTypeDesc() {
        return typeDesc;
    }

    public void setTypeDesc(String typeDesc) {
        this.typeDesc = typeDesc;
    }

    @CodeFieldNotes("")
    public String getRule() {
        return rule;
    }

    public void setRule(String rule) {
        this.rule = rule;
    }

    @CodeFieldNotes("")
    public Integer getMin() {
        return min;
    }

    public void setMin(Integer min) {
        this.min = min;
    }

    @CodeFieldNotes("")
    public Integer getMax() {
        return max;
    }

    public void setMax(Integer max) {
        this.max = max;
    }

    @CodeFieldNotes("")
    public String getRefObjectType() {
        return refObjectType;
    }

    public void setRefObjectType(String refObjectType) {
        this.refObjectType = refObjectType;
    }

    /**
     * 获取 是否为单据交易伙伴标识
     *
     * @return 是否为单据交易伙伴标识
     *
     * @mbggenerated
     */
    @CodeFieldNotes("是否为单据交易伙伴标识")
    public Integer getPartnerFlag() {
        return partnerFlag;
    }

    /**
     * 设置 是否为单据交易伙伴标识
     *
     * @return 是否为单据交易伙伴标识
     *
     * @mbggenerated
     */
    public void setPartnerFlag(Integer partnerFlag) {
        this.partnerFlag = partnerFlag;
    }

    @CodeFieldNotes("")
    public String getProgramSpEL() {
        return programSpEL;
    }

    public void setProgramSpEL(String programSpEL) {
        this.programSpEL = programSpEL;
    }

    @CodeFieldNotes("")
    public Integer getProgramMode() {
        return programMode;
    }

    public void setProgramMode(Integer programMode) {
        this.programMode = programMode;
    }

    /**
     * 获取 只读条件表达式
     *
     * @return 只读条件表达式
     *
     * @mbggenerated
     */
    @CodeFieldNotes("只读条件表达式")
    public String getReadonlyEval() {
        return readonlyEval;
    }

    /**
     * 设置 只读条件表达式
     *
     * @return 只读条件表达式
     *
     * @mbggenerated
     */
    public void setReadonlyEval(String readonlyEval) {
        this.readonlyEval = readonlyEval;
    }

    /**
     * 获取 选择框配置
     *
     * @return 选择框配置
     *
     * @mbggenerated
     */
    @CodeFieldNotes("选择框配置")
    public String getModalSelectorOptions() {
        return modalSelectorOptions;
    }

    /**
     * 设置 选择框配置
     *
     * @return 选择框配置
     *
     * @mbggenerated
     */
    public void setModalSelectorOptions(String modalSelectorOptions) {
        this.modalSelectorOptions = modalSelectorOptions;
    }

    @CodeFieldNotes("")
    public String getIndexKey() {
        return indexKey;
    }

    public void setIndexKey(String indexKey) {
        this.indexKey = indexKey;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    @CodeFieldNotes("")
    public Integer getOrderBy() {
        return orderBy;
    }

    public void setOrderBy(Integer orderBy) {
        this.orderBy = orderBy;
    }
}