package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DefDocComponent extends DefDocComponentKey implements Serializable {
    private String componentMapping;

    private String componentName;

    private Integer orderby;

    private Integer orderCalc;

    private Integer timesCalc;

    private String editableSpEL;

    private Long updatedTime;

    private Integer markdownFlag;

    private String markdown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_doc_component
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getComponentMapping() {
        return componentMapping;
    }

    public void setComponentMapping(String componentMapping) {
        this.componentMapping = componentMapping;
    }

    @CodeFieldNotes("")
    public String getComponentName() {
        return componentName;
    }

    public void setComponentName(String componentName) {
        this.componentName = componentName;
    }

    @CodeFieldNotes("")
    public Integer getOrderby() {
        return orderby;
    }

    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    @CodeFieldNotes("")
    public Integer getOrderCalc() {
        return orderCalc;
    }

    public void setOrderCalc(Integer orderCalc) {
        this.orderCalc = orderCalc;
    }

    @CodeFieldNotes("")
    public Integer getTimesCalc() {
        return timesCalc;
    }

    public void setTimesCalc(Integer timesCalc) {
        this.timesCalc = timesCalc;
    }

    @CodeFieldNotes("")
    public String getEditableSpEL() {
        return editableSpEL;
    }

    public void setEditableSpEL(String editableSpEL) {
        this.editableSpEL = editableSpEL;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    @CodeFieldNotes("")
    public Integer getMarkdownFlag() {
        return markdownFlag;
    }

    public void setMarkdownFlag(Integer markdownFlag) {
        this.markdownFlag = markdownFlag;
    }

    @CodeFieldNotes("")
    public String getMarkdown() {
        return markdown;
    }

    public void setMarkdown(String markdown) {
        this.markdown = markdown;
    }
}