package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class DefDocTypeKey implements Serializable {
    /**
     * 单据类型
     *
     * @mbggenerated
     */
    private String docType;

    /**
     * 暂时不启用，默认为1
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_doc_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 单据类型
     *
     * @return 单据类型
     *
     * @mbggenerated
     */
    @CodeFieldNotes("单据类型")
    public String getDocType() {
        return docType;
    }

    /**
     * 设置 单据类型
     *
     * @return 单据类型
     *
     * @mbggenerated
     */
    public void setDocType(String docType) {
        this.docType = docType;
    }

    /**
     * 获取 暂时不启用，默认为1
     *
     * @return 暂时不启用，默认为1
     *
     * @mbggenerated
     */
    @CodeFieldNotes("暂时不启用，默认为1")
    public Integer getVersion() {
        return version;
    }

    /**
     * 设置 暂时不启用，默认为1
     *
     * @return 暂时不启用，默认为1
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}