package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class DefDocStatusKey implements Serializable {
    private String docState;

    private String docType;

    private String preDocState;

    /**
     * 暂时不启用
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_doc_status
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getDocState() {
        return docState;
    }

    public void setDocState(String docState) {
        this.docState = docState;
    }

    @CodeFieldNotes("")
    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    @CodeFieldNotes("")
    public String getPreDocState() {
        return preDocState;
    }

    public void setPreDocState(String preDocState) {
        this.preDocState = preDocState;
    }

    /**
     * 获取 暂时不启用
     *
     * @return 暂时不启用
     *
     * @mbggenerated
     */
    @CodeFieldNotes("暂时不启用")
    public Integer getVersion() {
        return version;
    }

    /**
     * 设置 暂时不启用
     *
     * @return 暂时不启用
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}