package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class DefDocPartnerRoleKey implements Serializable {
    private String docType;

    /**
     * 交易伙伴角色
     *
     * @mbggenerated
     */
    private String role;

    /**
     * 业务类型
     *
     * @mbggenerated
     */
    private String type;

    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_doc_partner_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    /**
     * 获取 交易伙伴角色
     *
     * @return 交易伙伴角色
     *
     * @mbggenerated
     */
    @CodeFieldNotes("交易伙伴角色")
    public String getRole() {
        return role;
    }

    /**
     * 设置 交易伙伴角色
     *
     * @return 交易伙伴角色
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role;
    }

    /**
     * 获取 业务类型
     *
     * @return 业务类型
     *
     * @mbggenerated
     */
    @CodeFieldNotes("业务类型")
    public String getType() {
        return type;
    }

    /**
     * 设置 业务类型
     *
     * @return 业务类型
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type;
    }

    @CodeFieldNotes("")
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}