package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DefModalSelector extends DefModalSelectorKey implements Serializable {
    private String title;

    private String width;

    private String source;

    private String searchItemsJson;

    private String columnsJson;

    private String mappingsJson;

    private String preConditions;

    private Long updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @CodeFieldNotes("")
    public String getWidth() {
        return width;
    }

    public void setWidth(String width) {
        this.width = width;
    }

    @CodeFieldNotes("")
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @CodeFieldNotes("")
    public String getSearchItemsJson() {
        return searchItemsJson;
    }

    public void setSearchItemsJson(String searchItemsJson) {
        this.searchItemsJson = searchItemsJson;
    }

    @CodeFieldNotes("")
    public String getColumnsJson() {
        return columnsJson;
    }

    public void setColumnsJson(String columnsJson) {
        this.columnsJson = columnsJson;
    }

    @CodeFieldNotes("")
    public String getMappingsJson() {
        return mappingsJson;
    }

    public void setMappingsJson(String mappingsJson) {
        this.mappingsJson = mappingsJson;
    }

    @CodeFieldNotes("")
    public String getPreConditions() {
        return preConditions;
    }

    public void setPreConditions(String preConditions) {
        this.preConditions = preConditions;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }
}