package cn.nkpro.tfms.platform.model.po;

import java.util.ArrayList;
import java.util.List;

public class DefModalSelectorExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public DefModalSelectorExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andComponentIsNull() {
            addCriterion("COMPONENT is null");
            return (Criteria) this;
        }

        public Criteria andComponentIsNotNull() {
            addCriterion("COMPONENT is not null");
            return (Criteria) this;
        }

        public Criteria andComponentEqualTo(String value) {
            addCriterion("COMPONENT =", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentNotEqualTo(String value) {
            addCriterion("COMPONENT <>", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentGreaterThan(String value) {
            addCriterion("COMPONENT >", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentGreaterThanOrEqualTo(String value) {
            addCriterion("COMPONENT >=", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentLessThan(String value) {
            addCriterion("COMPONENT <", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentLessThanOrEqualTo(String value) {
            addCriterion("COMPONENT <=", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentLike(String value) {
            addCriterion("COMPONENT like", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentNotLike(String value) {
            addCriterion("COMPONENT not like", value, "component");
            return (Criteria) this;
        }

        public Criteria andComponentIn(List<String> values) {
            addCriterion("COMPONENT in", values, "component");
            return (Criteria) this;
        }

        public Criteria andComponentNotIn(List<String> values) {
            addCriterion("COMPONENT not in", values, "component");
            return (Criteria) this;
        }

        public Criteria andComponentBetween(String value1, String value2) {
            addCriterion("COMPONENT between", value1, value2, "component");
            return (Criteria) this;
        }

        public Criteria andComponentNotBetween(String value1, String value2) {
            addCriterion("COMPONENT not between", value1, value2, "component");
            return (Criteria) this;
        }

        public Criteria andDocTypeIsNull() {
            addCriterion("DOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDocTypeIsNotNull() {
            addCriterion("DOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDocTypeEqualTo(String value) {
            addCriterion("DOC_TYPE =", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotEqualTo(String value) {
            addCriterion("DOC_TYPE <>", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeGreaterThan(String value) {
            addCriterion("DOC_TYPE >", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_TYPE >=", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLessThan(String value) {
            addCriterion("DOC_TYPE <", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLessThanOrEqualTo(String value) {
            addCriterion("DOC_TYPE <=", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLike(String value) {
            addCriterion("DOC_TYPE like", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotLike(String value) {
            addCriterion("DOC_TYPE not like", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeIn(List<String> values) {
            addCriterion("DOC_TYPE in", values, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotIn(List<String> values) {
            addCriterion("DOC_TYPE not in", values, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeBetween(String value1, String value2) {
            addCriterion("DOC_TYPE between", value1, value2, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotBetween(String value1, String value2) {
            addCriterion("DOC_TYPE not between", value1, value2, "docType");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andWidthIsNull() {
            addCriterion("WIDTH is null");
            return (Criteria) this;
        }

        public Criteria andWidthIsNotNull() {
            addCriterion("WIDTH is not null");
            return (Criteria) this;
        }

        public Criteria andWidthEqualTo(String value) {
            addCriterion("WIDTH =", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotEqualTo(String value) {
            addCriterion("WIDTH <>", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThan(String value) {
            addCriterion("WIDTH >", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthGreaterThanOrEqualTo(String value) {
            addCriterion("WIDTH >=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThan(String value) {
            addCriterion("WIDTH <", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLessThanOrEqualTo(String value) {
            addCriterion("WIDTH <=", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthLike(String value) {
            addCriterion("WIDTH like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotLike(String value) {
            addCriterion("WIDTH not like", value, "width");
            return (Criteria) this;
        }

        public Criteria andWidthIn(List<String> values) {
            addCriterion("WIDTH in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotIn(List<String> values) {
            addCriterion("WIDTH not in", values, "width");
            return (Criteria) this;
        }

        public Criteria andWidthBetween(String value1, String value2) {
            addCriterion("WIDTH between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andWidthNotBetween(String value1, String value2) {
            addCriterion("WIDTH not between", value1, value2, "width");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonIsNull() {
            addCriterion("SEARCH_ITEMS_JSON is null");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonIsNotNull() {
            addCriterion("SEARCH_ITEMS_JSON is not null");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonEqualTo(String value) {
            addCriterion("SEARCH_ITEMS_JSON =", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonNotEqualTo(String value) {
            addCriterion("SEARCH_ITEMS_JSON <>", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonGreaterThan(String value) {
            addCriterion("SEARCH_ITEMS_JSON >", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonGreaterThanOrEqualTo(String value) {
            addCriterion("SEARCH_ITEMS_JSON >=", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonLessThan(String value) {
            addCriterion("SEARCH_ITEMS_JSON <", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonLessThanOrEqualTo(String value) {
            addCriterion("SEARCH_ITEMS_JSON <=", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonLike(String value) {
            addCriterion("SEARCH_ITEMS_JSON like", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonNotLike(String value) {
            addCriterion("SEARCH_ITEMS_JSON not like", value, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonIn(List<String> values) {
            addCriterion("SEARCH_ITEMS_JSON in", values, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonNotIn(List<String> values) {
            addCriterion("SEARCH_ITEMS_JSON not in", values, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonBetween(String value1, String value2) {
            addCriterion("SEARCH_ITEMS_JSON between", value1, value2, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andSearchItemsJsonNotBetween(String value1, String value2) {
            addCriterion("SEARCH_ITEMS_JSON not between", value1, value2, "searchItemsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonIsNull() {
            addCriterion("COLUMNS_JSON is null");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonIsNotNull() {
            addCriterion("COLUMNS_JSON is not null");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonEqualTo(String value) {
            addCriterion("COLUMNS_JSON =", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonNotEqualTo(String value) {
            addCriterion("COLUMNS_JSON <>", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonGreaterThan(String value) {
            addCriterion("COLUMNS_JSON >", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMNS_JSON >=", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonLessThan(String value) {
            addCriterion("COLUMNS_JSON <", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonLessThanOrEqualTo(String value) {
            addCriterion("COLUMNS_JSON <=", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonLike(String value) {
            addCriterion("COLUMNS_JSON like", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonNotLike(String value) {
            addCriterion("COLUMNS_JSON not like", value, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonIn(List<String> values) {
            addCriterion("COLUMNS_JSON in", values, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonNotIn(List<String> values) {
            addCriterion("COLUMNS_JSON not in", values, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonBetween(String value1, String value2) {
            addCriterion("COLUMNS_JSON between", value1, value2, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andColumnsJsonNotBetween(String value1, String value2) {
            addCriterion("COLUMNS_JSON not between", value1, value2, "columnsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonIsNull() {
            addCriterion("MAPPINGS_JSON is null");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonIsNotNull() {
            addCriterion("MAPPINGS_JSON is not null");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonEqualTo(String value) {
            addCriterion("MAPPINGS_JSON =", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonNotEqualTo(String value) {
            addCriterion("MAPPINGS_JSON <>", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonGreaterThan(String value) {
            addCriterion("MAPPINGS_JSON >", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonGreaterThanOrEqualTo(String value) {
            addCriterion("MAPPINGS_JSON >=", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonLessThan(String value) {
            addCriterion("MAPPINGS_JSON <", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonLessThanOrEqualTo(String value) {
            addCriterion("MAPPINGS_JSON <=", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonLike(String value) {
            addCriterion("MAPPINGS_JSON like", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonNotLike(String value) {
            addCriterion("MAPPINGS_JSON not like", value, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonIn(List<String> values) {
            addCriterion("MAPPINGS_JSON in", values, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonNotIn(List<String> values) {
            addCriterion("MAPPINGS_JSON not in", values, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonBetween(String value1, String value2) {
            addCriterion("MAPPINGS_JSON between", value1, value2, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andMappingsJsonNotBetween(String value1, String value2) {
            addCriterion("MAPPINGS_JSON not between", value1, value2, "mappingsJson");
            return (Criteria) this;
        }

        public Criteria andPreConditionsIsNull() {
            addCriterion("PRE_CONDITIONS is null");
            return (Criteria) this;
        }

        public Criteria andPreConditionsIsNotNull() {
            addCriterion("PRE_CONDITIONS is not null");
            return (Criteria) this;
        }

        public Criteria andPreConditionsEqualTo(String value) {
            addCriterion("PRE_CONDITIONS =", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsNotEqualTo(String value) {
            addCriterion("PRE_CONDITIONS <>", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsGreaterThan(String value) {
            addCriterion("PRE_CONDITIONS >", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_CONDITIONS >=", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsLessThan(String value) {
            addCriterion("PRE_CONDITIONS <", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsLessThanOrEqualTo(String value) {
            addCriterion("PRE_CONDITIONS <=", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsLike(String value) {
            addCriterion("PRE_CONDITIONS like", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsNotLike(String value) {
            addCriterion("PRE_CONDITIONS not like", value, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsIn(List<String> values) {
            addCriterion("PRE_CONDITIONS in", values, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsNotIn(List<String> values) {
            addCriterion("PRE_CONDITIONS not in", values, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsBetween(String value1, String value2) {
            addCriterion("PRE_CONDITIONS between", value1, value2, "preConditions");
            return (Criteria) this;
        }

        public Criteria andPreConditionsNotBetween(String value1, String value2) {
            addCriterion("PRE_CONDITIONS not between", value1, value2, "preConditions");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Long value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Long value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Long value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Long value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Long> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Long> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_modal_selector
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_modal_selector
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}