package cn.nkpro.tfms.platform.model.po;

import java.util.ArrayList;
import java.util.List;

public class DefPartnerRoleDocExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public DefPartnerRoleDocExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDocTypeIsNull() {
            addCriterion("DOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDocTypeIsNotNull() {
            addCriterion("DOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDocTypeEqualTo(String value) {
            addCriterion("DOC_TYPE =", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotEqualTo(String value) {
            addCriterion("DOC_TYPE <>", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeGreaterThan(String value) {
            addCriterion("DOC_TYPE >", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeGreaterThanOrEqualTo(String value) {
            addCriterion("DOC_TYPE >=", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLessThan(String value) {
            addCriterion("DOC_TYPE <", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLessThanOrEqualTo(String value) {
            addCriterion("DOC_TYPE <=", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeLike(String value) {
            addCriterion("DOC_TYPE like", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotLike(String value) {
            addCriterion("DOC_TYPE not like", value, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeIn(List<String> values) {
            addCriterion("DOC_TYPE in", values, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotIn(List<String> values) {
            addCriterion("DOC_TYPE not in", values, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeBetween(String value1, String value2) {
            addCriterion("DOC_TYPE between", value1, value2, "docType");
            return (Criteria) this;
        }

        public Criteria andDocTypeNotBetween(String value1, String value2) {
            addCriterion("DOC_TYPE not between", value1, value2, "docType");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleIsNull() {
            addCriterion("PARTNER_ROLE is null");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleIsNotNull() {
            addCriterion("PARTNER_ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleEqualTo(String value) {
            addCriterion("PARTNER_ROLE =", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotEqualTo(String value) {
            addCriterion("PARTNER_ROLE <>", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleGreaterThan(String value) {
            addCriterion("PARTNER_ROLE >", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleGreaterThanOrEqualTo(String value) {
            addCriterion("PARTNER_ROLE >=", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleLessThan(String value) {
            addCriterion("PARTNER_ROLE <", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleLessThanOrEqualTo(String value) {
            addCriterion("PARTNER_ROLE <=", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleLike(String value) {
            addCriterion("PARTNER_ROLE like", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotLike(String value) {
            addCriterion("PARTNER_ROLE not like", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleIn(List<String> values) {
            addCriterion("PARTNER_ROLE in", values, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotIn(List<String> values) {
            addCriterion("PARTNER_ROLE not in", values, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleBetween(String value1, String value2) {
            addCriterion("PARTNER_ROLE between", value1, value2, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotBetween(String value1, String value2) {
            addCriterion("PARTNER_ROLE not between", value1, value2, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeIsNull() {
            addCriterion("PRE_DOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeIsNotNull() {
            addCriterion("PRE_DOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeEqualTo(String value) {
            addCriterion("PRE_DOC_TYPE =", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeNotEqualTo(String value) {
            addCriterion("PRE_DOC_TYPE <>", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeGreaterThan(String value) {
            addCriterion("PRE_DOC_TYPE >", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_DOC_TYPE >=", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeLessThan(String value) {
            addCriterion("PRE_DOC_TYPE <", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeLessThanOrEqualTo(String value) {
            addCriterion("PRE_DOC_TYPE <=", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeLike(String value) {
            addCriterion("PRE_DOC_TYPE like", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeNotLike(String value) {
            addCriterion("PRE_DOC_TYPE not like", value, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeIn(List<String> values) {
            addCriterion("PRE_DOC_TYPE in", values, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeNotIn(List<String> values) {
            addCriterion("PRE_DOC_TYPE not in", values, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeBetween(String value1, String value2) {
            addCriterion("PRE_DOC_TYPE between", value1, value2, "preDocType");
            return (Criteria) this;
        }

        public Criteria andPreDocTypeNotBetween(String value1, String value2) {
            addCriterion("PRE_DOC_TYPE not between", value1, value2, "preDocType");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Long value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Long value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Long value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Long value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Long> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Long> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andOrderbyIsNull() {
            addCriterion("ORDERBY is null");
            return (Criteria) this;
        }

        public Criteria andOrderbyIsNotNull() {
            addCriterion("ORDERBY is not null");
            return (Criteria) this;
        }

        public Criteria andOrderbyEqualTo(Integer value) {
            addCriterion("ORDERBY =", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotEqualTo(Integer value) {
            addCriterion("ORDERBY <>", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyGreaterThan(Integer value) {
            addCriterion("ORDERBY >", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyGreaterThanOrEqualTo(Integer value) {
            addCriterion("ORDERBY >=", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyLessThan(Integer value) {
            addCriterion("ORDERBY <", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyLessThanOrEqualTo(Integer value) {
            addCriterion("ORDERBY <=", value, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyIn(List<Integer> values) {
            addCriterion("ORDERBY in", values, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotIn(List<Integer> values) {
            addCriterion("ORDERBY not in", values, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyBetween(Integer value1, Integer value2) {
            addCriterion("ORDERBY between", value1, value2, "orderby");
            return (Criteria) this;
        }

        public Criteria andOrderbyNotBetween(Integer value1, Integer value2) {
            addCriterion("ORDERBY not between", value1, value2, "orderby");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusIsNull() {
            addCriterion("PRE_DOC_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusIsNotNull() {
            addCriterion("PRE_DOC_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusEqualTo(String value) {
            addCriterion("PRE_DOC_STATUS =", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusNotEqualTo(String value) {
            addCriterion("PRE_DOC_STATUS <>", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusGreaterThan(String value) {
            addCriterion("PRE_DOC_STATUS >", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusGreaterThanOrEqualTo(String value) {
            addCriterion("PRE_DOC_STATUS >=", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusLessThan(String value) {
            addCriterion("PRE_DOC_STATUS <", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusLessThanOrEqualTo(String value) {
            addCriterion("PRE_DOC_STATUS <=", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusLike(String value) {
            addCriterion("PRE_DOC_STATUS like", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusNotLike(String value) {
            addCriterion("PRE_DOC_STATUS not like", value, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusIn(List<String> values) {
            addCriterion("PRE_DOC_STATUS in", values, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusNotIn(List<String> values) {
            addCriterion("PRE_DOC_STATUS not in", values, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusBetween(String value1, String value2) {
            addCriterion("PRE_DOC_STATUS between", value1, value2, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andPreDocStatusNotBetween(String value1, String value2) {
            addCriterion("PRE_DOC_STATUS not between", value1, value2, "preDocStatus");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeIsNull() {
            addCriterion("REF_OBJECT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeIsNotNull() {
            addCriterion("REF_OBJECT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE =", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE <>", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeGreaterThan(String value) {
            addCriterion("REF_OBJECT_TYPE >", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE >=", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeLessThan(String value) {
            addCriterion("REF_OBJECT_TYPE <", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeLessThanOrEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE <=", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeLike(String value) {
            addCriterion("REF_OBJECT_TYPE like", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotLike(String value) {
            addCriterion("REF_OBJECT_TYPE not like", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeIn(List<String> values) {
            addCriterion("REF_OBJECT_TYPE in", values, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotIn(List<String> values) {
            addCriterion("REF_OBJECT_TYPE not in", values, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeBetween(String value1, String value2) {
            addCriterion("REF_OBJECT_TYPE between", value1, value2, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotBetween(String value1, String value2) {
            addCriterion("REF_OBJECT_TYPE not between", value1, value2, "refObjectType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_partner_role_doc
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}