package cn.nkpro.tfms.platform.model.po;

import java.util.ArrayList;
import java.util.List;

public class DefPartnerRoleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public DefPartnerRoleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPartnerRoleIsNull() {
            addCriterion("PARTNER_ROLE is null");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleIsNotNull() {
            addCriterion("PARTNER_ROLE is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleEqualTo(String value) {
            addCriterion("PARTNER_ROLE =", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotEqualTo(String value) {
            addCriterion("PARTNER_ROLE <>", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleGreaterThan(String value) {
            addCriterion("PARTNER_ROLE >", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleGreaterThanOrEqualTo(String value) {
            addCriterion("PARTNER_ROLE >=", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleLessThan(String value) {
            addCriterion("PARTNER_ROLE <", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleLessThanOrEqualTo(String value) {
            addCriterion("PARTNER_ROLE <=", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleLike(String value) {
            addCriterion("PARTNER_ROLE like", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotLike(String value) {
            addCriterion("PARTNER_ROLE not like", value, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleIn(List<String> values) {
            addCriterion("PARTNER_ROLE in", values, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotIn(List<String> values) {
            addCriterion("PARTNER_ROLE not in", values, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleBetween(String value1, String value2) {
            addCriterion("PARTNER_ROLE between", value1, value2, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleNotBetween(String value1, String value2) {
            addCriterion("PARTNER_ROLE not between", value1, value2, "partnerRole");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescIsNull() {
            addCriterion("PARTNER_ROLE_DESC is null");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescIsNotNull() {
            addCriterion("PARTNER_ROLE_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescEqualTo(String value) {
            addCriterion("PARTNER_ROLE_DESC =", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescNotEqualTo(String value) {
            addCriterion("PARTNER_ROLE_DESC <>", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescGreaterThan(String value) {
            addCriterion("PARTNER_ROLE_DESC >", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescGreaterThanOrEqualTo(String value) {
            addCriterion("PARTNER_ROLE_DESC >=", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescLessThan(String value) {
            addCriterion("PARTNER_ROLE_DESC <", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescLessThanOrEqualTo(String value) {
            addCriterion("PARTNER_ROLE_DESC <=", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescLike(String value) {
            addCriterion("PARTNER_ROLE_DESC like", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescNotLike(String value) {
            addCriterion("PARTNER_ROLE_DESC not like", value, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescIn(List<String> values) {
            addCriterion("PARTNER_ROLE_DESC in", values, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescNotIn(List<String> values) {
            addCriterion("PARTNER_ROLE_DESC not in", values, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescBetween(String value1, String value2) {
            addCriterion("PARTNER_ROLE_DESC between", value1, value2, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andPartnerRoleDescNotBetween(String value1, String value2) {
            addCriterion("PARTNER_ROLE_DESC not between", value1, value2, "partnerRoleDesc");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeIsNull() {
            addCriterion("REF_OBJECT_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeIsNotNull() {
            addCriterion("REF_OBJECT_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE =", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE <>", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeGreaterThan(String value) {
            addCriterion("REF_OBJECT_TYPE >", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE >=", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeLessThan(String value) {
            addCriterion("REF_OBJECT_TYPE <", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeLessThanOrEqualTo(String value) {
            addCriterion("REF_OBJECT_TYPE <=", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeLike(String value) {
            addCriterion("REF_OBJECT_TYPE like", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotLike(String value) {
            addCriterion("REF_OBJECT_TYPE not like", value, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeIn(List<String> values) {
            addCriterion("REF_OBJECT_TYPE in", values, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotIn(List<String> values) {
            addCriterion("REF_OBJECT_TYPE not in", values, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeBetween(String value1, String value2) {
            addCriterion("REF_OBJECT_TYPE between", value1, value2, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andRefObjectTypeNotBetween(String value1, String value2) {
            addCriterion("REF_OBJECT_TYPE not between", value1, value2, "refObjectType");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("UPDATED_TIME is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("UPDATED_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Long value) {
            addCriterion("UPDATED_TIME =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Long value) {
            addCriterion("UPDATED_TIME <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Long value) {
            addCriterion("UPDATED_TIME >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Long value) {
            addCriterion("UPDATED_TIME <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Long value) {
            addCriterion("UPDATED_TIME <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Long> values) {
            addCriterion("UPDATED_TIME in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Long> values) {
            addCriterion("UPDATED_TIME not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Long value1, Long value2) {
            addCriterion("UPDATED_TIME not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeIsNull() {
            addCriterion("REF_DOC_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeIsNotNull() {
            addCriterion("REF_DOC_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeEqualTo(String value) {
            addCriterion("REF_DOC_TYPE =", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeNotEqualTo(String value) {
            addCriterion("REF_DOC_TYPE <>", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeGreaterThan(String value) {
            addCriterion("REF_DOC_TYPE >", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REF_DOC_TYPE >=", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeLessThan(String value) {
            addCriterion("REF_DOC_TYPE <", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeLessThanOrEqualTo(String value) {
            addCriterion("REF_DOC_TYPE <=", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeLike(String value) {
            addCriterion("REF_DOC_TYPE like", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeNotLike(String value) {
            addCriterion("REF_DOC_TYPE not like", value, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeIn(List<String> values) {
            addCriterion("REF_DOC_TYPE in", values, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeNotIn(List<String> values) {
            addCriterion("REF_DOC_TYPE not in", values, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeBetween(String value1, String value2) {
            addCriterion("REF_DOC_TYPE between", value1, value2, "refDocType");
            return (Criteria) this;
        }

        public Criteria andRefDocTypeNotBetween(String value1, String value2) {
            addCriterion("REF_DOC_TYPE not between", value1, value2, "refDocType");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("STATE is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("STATE is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("STATE =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("STATE <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("STATE >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("STATE >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("STATE <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("STATE <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("STATE like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("STATE not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("STATE in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("STATE not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("STATE between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("STATE not between", value1, value2, "state");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_partner_role
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table def_partner_role
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}