package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DefProjectType extends DefProjectTypeKey implements Serializable {
    /**
     * 项目类型描述
     *
     * @mbggenerated
     */
    private String projectTypeDesc;

    /**
     * 有效期自
     *
     * @mbggenerated
     */
    private String validFrom;

    /**
     * 有效期至
     *
     * @mbggenerated
     */
    private String validTo;

    /**
     * java扩展
     *
     * @mbggenerated
     */
    private String refObjectType;

    /**
     * 最后修改时间秒数
     *
     * @mbggenerated
     */
    private Long updatedTime;

    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_project_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 项目类型描述
     *
     * @return 项目类型描述
     *
     * @mbggenerated
     */
    @CodeFieldNotes("项目类型描述")
    public String getProjectTypeDesc() {
        return projectTypeDesc;
    }

    /**
     * 设置 项目类型描述
     *
     * @return 项目类型描述
     *
     * @mbggenerated
     */
    public void setProjectTypeDesc(String projectTypeDesc) {
        this.projectTypeDesc = projectTypeDesc;
    }

    /**
     * 获取 有效期自
     *
     * @return 有效期自
     *
     * @mbggenerated
     */
    @CodeFieldNotes("有效期自")
    public String getValidFrom() {
        return validFrom;
    }

    /**
     * 设置 有效期自
     *
     * @return 有效期自
     *
     * @mbggenerated
     */
    public void setValidFrom(String validFrom) {
        this.validFrom = validFrom;
    }

    /**
     * 获取 有效期至
     *
     * @return 有效期至
     *
     * @mbggenerated
     */
    @CodeFieldNotes("有效期至")
    public String getValidTo() {
        return validTo;
    }

    /**
     * 设置 有效期至
     *
     * @return 有效期至
     *
     * @mbggenerated
     */
    public void setValidTo(String validTo) {
        this.validTo = validTo;
    }

    /**
     * 获取 java扩展
     *
     * @return java扩展
     *
     * @mbggenerated
     */
    @CodeFieldNotes("java扩展")
    public String getRefObjectType() {
        return refObjectType;
    }

    /**
     * 设置 java扩展
     *
     * @return java扩展
     *
     * @mbggenerated
     */
    public void setRefObjectType(String refObjectType) {
        this.refObjectType = refObjectType;
    }

    /**
     * 获取 最后修改时间秒数
     *
     * @return 最后修改时间秒数
     *
     * @mbggenerated
     */
    @CodeFieldNotes("最后修改时间秒数")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    /**
     * 设置 最后修改时间秒数
     *
     * @return 最后修改时间秒数
     *
     * @mbggenerated
     */
    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    @CodeFieldNotes("")
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }
}