package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class DefProjectDocKey implements Serializable {
    private String docType;

    private String preDocType;

    private String projectType;

    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_project_doc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    @CodeFieldNotes("")
    public String getPreDocType() {
        return preDocType;
    }

    public void setPreDocType(String preDocType) {
        this.preDocType = preDocType;
    }

    @CodeFieldNotes("")
    public String getProjectType() {
        return projectType;
    }

    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }

    @CodeFieldNotes("")
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}