package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class DefProjectTypeKey implements Serializable {
    /**
     * 项目类型
     *
     * @mbggenerated
     */
    private String projectType;

    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_project_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 项目类型
     *
     * @return 项目类型
     *
     * @mbggenerated
     */
    @CodeFieldNotes("项目类型")
    public String getProjectType() {
        return projectType;
    }

    /**
     * 设置 项目类型
     *
     * @return 项目类型
     *
     * @mbggenerated
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType;
    }

    @CodeFieldNotes("")
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }
}