package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class DefProjectDoc extends DefProjectDocKey implements Serializable {
    /**
     * 前置项目状态条件
     *
     * @mbggenerated
     */
    private String preProjectStatus;

    /**
     * 前置单据状态条件
     *
     * @mbggenerated
     */
    private String preDocStatus;

    private Integer docCountLimit;

    private String refObjectType;

    private Long updatedTime;

    private Integer orderby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_project_doc
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 获取 前置项目状态条件
     *
     * @return 前置项目状态条件
     *
     * @mbggenerated
     */
    @CodeFieldNotes("前置项目状态条件")
    public String getPreProjectStatus() {
        return preProjectStatus;
    }

    /**
     * 设置 前置项目状态条件
     *
     * @return 前置项目状态条件
     *
     * @mbggenerated
     */
    public void setPreProjectStatus(String preProjectStatus) {
        this.preProjectStatus = preProjectStatus;
    }

    /**
     * 获取 前置单据状态条件
     *
     * @return 前置单据状态条件
     *
     * @mbggenerated
     */
    @CodeFieldNotes("前置单据状态条件")
    public String getPreDocStatus() {
        return preDocStatus;
    }

    /**
     * 设置 前置单据状态条件
     *
     * @return 前置单据状态条件
     *
     * @mbggenerated
     */
    public void setPreDocStatus(String preDocStatus) {
        this.preDocStatus = preDocStatus;
    }

    @CodeFieldNotes("")
    public Integer getDocCountLimit() {
        return docCountLimit;
    }

    public void setDocCountLimit(Integer docCountLimit) {
        this.docCountLimit = docCountLimit;
    }

    @CodeFieldNotes("")
    public String getRefObjectType() {
        return refObjectType;
    }

    public void setRefObjectType(String refObjectType) {
        this.refObjectType = refObjectType;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    @CodeFieldNotes("")
    public Integer getOrderby() {
        return orderby;
    }

    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }
}