package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class DefServiceStatusManagerKey implements Serializable {
    private String condState;

    private String docType;

    private String targetDocType;

    private String targetType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table def_service_status_manager
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getCondState() {
        return condState;
    }

    public void setCondState(String condState) {
        this.condState = condState;
    }

    @CodeFieldNotes("")
    public String getDocType() {
        return docType;
    }

    public void setDocType(String docType) {
        this.docType = docType;
    }

    @CodeFieldNotes("")
    public String getTargetDocType() {
        return targetDocType;
    }

    public void setTargetDocType(String targetDocType) {
        this.targetDocType = targetDocType;
    }

    @CodeFieldNotes("")
    public String getTargetType() {
        return targetType;
    }

    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }
}