package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SysAuthPermission implements Serializable {
    private String permId;

    private String permDesc;

    /**
     * 资源，如单据 D:ZR01 
     *
     * @mbggenerated
     */
    private String permResource;

    /**
     * 操作 CRUD
     *
     * @mbggenerated
     */
    private String permOperate;

    /**
     * 限制，主要针对数据权限控制
     *
     * @mbggenerated
     */
    private String limitId;

    private String permLevel;

    /**
     * 子资源，如卡片
     *
     * @mbggenerated
     */
    private String subResource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_auth_permission
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getPermId() {
        return permId;
    }

    public void setPermId(String permId) {
        this.permId = permId;
    }

    @CodeFieldNotes("")
    public String getPermDesc() {
        return permDesc;
    }

    public void setPermDesc(String permDesc) {
        this.permDesc = permDesc;
    }

    /**
     * 获取 资源，如单据 D:ZR01 
     *
     * @return 资源，如单据 D:ZR01 
     *
     * @mbggenerated
     */
    @CodeFieldNotes("资源，如单据 D:ZR01 ")
    public String getPermResource() {
        return permResource;
    }

    /**
     * 设置 资源，如单据 D:ZR01 
     *
     * @return 资源，如单据 D:ZR01 
     *
     * @mbggenerated
     */
    public void setPermResource(String permResource) {
        this.permResource = permResource;
    }

    /**
     * 获取 操作 CRUD
     *
     * @return 操作 CRUD
     *
     * @mbggenerated
     */
    @CodeFieldNotes("操作 CRUD")
    public String getPermOperate() {
        return permOperate;
    }

    /**
     * 设置 操作 CRUD
     *
     * @return 操作 CRUD
     *
     * @mbggenerated
     */
    public void setPermOperate(String permOperate) {
        this.permOperate = permOperate;
    }

    /**
     * 获取 限制，主要针对数据权限控制
     *
     * @return 限制，主要针对数据权限控制
     *
     * @mbggenerated
     */
    @CodeFieldNotes("限制，主要针对数据权限控制")
    public String getLimitId() {
        return limitId;
    }

    /**
     * 设置 限制，主要针对数据权限控制
     *
     * @return 限制，主要针对数据权限控制
     *
     * @mbggenerated
     */
    public void setLimitId(String limitId) {
        this.limitId = limitId;
    }

    @CodeFieldNotes("")
    public String getPermLevel() {
        return permLevel;
    }

    public void setPermLevel(String permLevel) {
        this.permLevel = permLevel;
    }

    /**
     * 获取 子资源，如卡片
     *
     * @return 子资源，如卡片
     *
     * @mbggenerated
     */
    @CodeFieldNotes("子资源，如卡片")
    public String getSubResource() {
        return subResource;
    }

    /**
     * 设置 子资源，如卡片
     *
     * @return 子资源，如卡片
     *
     * @mbggenerated
     */
    public void setSubResource(String subResource) {
        this.subResource = subResource;
    }
}