package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SysAuthLimit implements Serializable {
    private String limitId;

    private String limitDesc;

    private String limitLevel;

    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_auth_limit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getLimitId() {
        return limitId;
    }

    public void setLimitId(String limitId) {
        this.limitId = limitId;
    }

    @CodeFieldNotes("")
    public String getLimitDesc() {
        return limitDesc;
    }

    public void setLimitDesc(String limitDesc) {
        this.limitDesc = limitDesc;
    }

    @CodeFieldNotes("")
    public String getLimitLevel() {
        return limitLevel;
    }

    public void setLimitLevel(String limitLevel) {
        this.limitLevel = limitLevel;
    }

    @CodeFieldNotes("")
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }
}