package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class SysAuthGroupRefKey implements Serializable {
    private String groupId;

    private String refId;

    /**
     * 0 account 1 permission 2 limit
     *
     * @mbggenerated
     */
    private Integer refType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_auth_group_ref
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    @CodeFieldNotes("")
    public String getRefId() {
        return refId;
    }

    public void setRefId(String refId) {
        this.refId = refId;
    }

    /**
     * 获取 0 account 1 permission 2 limit
     *
     * @return 0 account 1 permission 2 limit
     *
     * @mbggenerated
     */
    @CodeFieldNotes("0 account 1 permission 2 limit")
    public Integer getRefType() {
        return refType;
    }

    /**
     * 设置 0 account 1 permission 2 limit
     *
     * @return 0 account 1 permission 2 limit
     *
     * @mbggenerated
     */
    public void setRefType(Integer refType) {
        this.refType = refType;
    }
}