package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import java.io.Serializable;

@JsonIgnoreProperties(ignoreUnknown = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class SysLogDocRecord implements Serializable {
    private String id;

    private String docId;

    private Integer version;

    private String stateOriginal;

    private String stateOriginalDesc;

    private String state;

    private String stateDesc;

    private String cardNames;

    private String userId;

    private String userRealname;

    private String source;

    private String logGroupId;

    private Long updatedTime;

    private String data;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_log_doc_record
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @CodeFieldNotes("")
    public String getDocId() {
        return docId;
    }

    public void setDocId(String docId) {
        this.docId = docId;
    }

    @CodeFieldNotes("")
    public Integer getVersion() {
        return version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    @CodeFieldNotes("")
    public String getStateOriginal() {
        return stateOriginal;
    }

    public void setStateOriginal(String stateOriginal) {
        this.stateOriginal = stateOriginal;
    }

    @CodeFieldNotes("")
    public String getStateOriginalDesc() {
        return stateOriginalDesc;
    }

    public void setStateOriginalDesc(String stateOriginalDesc) {
        this.stateOriginalDesc = stateOriginalDesc;
    }

    @CodeFieldNotes("")
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @CodeFieldNotes("")
    public String getStateDesc() {
        return stateDesc;
    }

    public void setStateDesc(String stateDesc) {
        this.stateDesc = stateDesc;
    }

    @CodeFieldNotes("")
    public String getCardNames() {
        return cardNames;
    }

    public void setCardNames(String cardNames) {
        this.cardNames = cardNames;
    }

    @CodeFieldNotes("")
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @CodeFieldNotes("")
    public String getUserRealname() {
        return userRealname;
    }

    public void setUserRealname(String userRealname) {
        this.userRealname = userRealname;
    }

    @CodeFieldNotes("")
    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    @CodeFieldNotes("")
    public String getLogGroupId() {
        return logGroupId;
    }

    public void setLogGroupId(String logGroupId) {
        this.logGroupId = logGroupId;
    }

    @CodeFieldNotes("")
    public Long getUpdatedTime() {
        return updatedTime;
    }

    public void setUpdatedTime(Long updatedTime) {
        this.updatedTime = updatedTime;
    }

    @CodeFieldNotes("")
    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }
}