package cn.nkpro.tfms.platform.model.po;

import cn.nkpro.ts5.basic.wsdoc.annotation.CodeFieldNotes;

import java.io.Serializable;

public class SysUserDashboardRefKey implements Serializable {
    private String accountId;

    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_user_dashboard_ref
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    @CodeFieldNotes("")
    public String getAccountId() {
        return accountId;
    }

    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    @CodeFieldNotes("")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}